[project]
name = "postgres-range-repro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django==4.2.17",
    "django-environ>=0.11.2",
    "psycopg2-binary>=2.9.10",
]
