# Generated by Django 4.2.17 on 2025-01-09 14:21

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
            ],
        ),
    ]
